
// FILE GENERATED BY TpmExtractCode: DO NOT EDIT

#ifndef _COMMANDS_H_
#define _COMMANDS_H_

#if CC_Startup
#include "TPM/TPMCmd/tpm/include/private/prototypes/Startup_fp.h"
#endif
#if CC_Shutdown
#include "TPM/TPMCmd/tpm/include/private/prototypes/Shutdown_fp.h"
#endif
#if CC_SelfTest
#include "TPM/TPMCmd/tpm/include/private/prototypes/SelfTest_fp.h"
#endif
#if CC_IncrementalSelfTest
#include "TPM/TPMCmd/tpm/include/private/prototypes/IncrementalSelfTest_fp.h"
#endif
#if CC_GetTestResult
#include "TPM/TPMCmd/tpm/include/private/prototypes/GetTestResult_fp.h"
#endif
#if CC_StartAuthSession
#include "TPM/TPMCmd/tpm/include/private/prototypes/StartAuthSession_fp.h"
#endif
#if CC_PolicyRestart
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicyRestart_fp.h"
#endif
#if CC_Create
#include "TPM/TPMCmd/tpm/include/private/prototypes/Create_fp.h"
#endif
#if CC_Load
#include "TPM/TPMCmd/tpm/include/private/prototypes/Load_fp.h"
#endif
#if CC_LoadExternal
#include "TPM/TPMCmd/tpm/include/private/prototypes/LoadExternal_fp.h"
#endif
#if CC_ReadPublic
#include "TPM/TPMCmd/tpm/include/private/prototypes/ReadPublic_fp.h"
#endif
#if CC_ActivateCredential
#include "TPM/TPMCmd/tpm/include/private/prototypes/ActivateCredential_fp.h"
#endif
#if CC_MakeCredential
#include "TPM/TPMCmd/tpm/include/private/prototypes/MakeCredential_fp.h"
#endif
#if CC_Unseal
#include "TPM/TPMCmd/tpm/include/private/prototypes/Unseal_fp.h"
#endif
#if CC_ObjectChangeAuth
#include "TPM/TPMCmd/tpm/include/private/prototypes/ObjectChangeAuth_fp.h"
#endif
#if CC_CreateLoaded
#include "TPM/TPMCmd/tpm/include/private/prototypes/CreateLoaded_fp.h"
#endif
#if CC_Duplicate
#include "TPM/TPMCmd/tpm/include/private/prototypes/Duplicate_fp.h"
#endif
#if CC_Rewrap
#include "TPM/TPMCmd/tpm/include/private/prototypes/Rewrap_fp.h"
#endif
#if CC_Import
#include "TPM/TPMCmd/tpm/include/private/prototypes/Import_fp.h"
#endif
#if CC_RSA_Encrypt
#include "TPM/TPMCmd/tpm/include/private/prototypes/RSA_Encrypt_fp.h"
#endif
#if CC_RSA_Decrypt
#include "TPM/TPMCmd/tpm/include/private/prototypes/RSA_Decrypt_fp.h"
#endif
#if CC_ECDH_KeyGen
#include "TPM/TPMCmd/tpm/include/private/prototypes/ECDH_KeyGen_fp.h"
#endif
#if CC_ECDH_ZGen
#include "TPM/TPMCmd/tpm/include/private/prototypes/ECDH_ZGen_fp.h"
#endif
#if CC_ECC_Parameters
#include "TPM/TPMCmd/tpm/include/private/prototypes/ECC_Parameters_fp.h"
#endif
#if CC_ZGen_2Phase
#include "TPM/TPMCmd/tpm/include/private/prototypes/ZGen_2Phase_fp.h"
#endif
#if CC_ECC_Encrypt
#include "TPM/TPMCmd/tpm/include/private/prototypes/ECC_Encrypt_fp.h"
#endif
#if CC_ECC_Decrypt
#include "TPM/TPMCmd/tpm/include/private/prototypes/ECC_Decrypt_fp.h"
#endif
#if CC_EncryptDecrypt
#include "TPM/TPMCmd/tpm/include/private/prototypes/EncryptDecrypt_fp.h"
#endif
#if CC_EncryptDecrypt2
#include "TPM/TPMCmd/tpm/include/private/prototypes/EncryptDecrypt2_fp.h"
#endif
#if CC_Hash
#include "TPM/TPMCmd/tpm/include/private/prototypes/Hash_fp.h"
#endif
#if CC_HMAC
#include "TPM/TPMCmd/tpm/include/private/prototypes/HMAC_fp.h"
#endif
#if CC_MAC
#include "TPM/TPMCmd/tpm/include/private/prototypes/MAC_fp.h"
#endif
#if CC_GetRandom
#include "TPM/TPMCmd/tpm/include/private/prototypes/GetRandom_fp.h"
#endif
#if CC_StirRandom
#include "TPM/TPMCmd/tpm/include/private/prototypes/StirRandom_fp.h"
#endif
#if CC_HMAC_Start
#include "TPM/TPMCmd/tpm/include/private/prototypes/HMAC_Start_fp.h"
#endif
#if CC_MAC_Start
#include "TPM/TPMCmd/tpm/include/private/prototypes/MAC_Start_fp.h"
#endif
#if CC_HashSequenceStart
#include "TPM/TPMCmd/tpm/include/private/prototypes/HashSequenceStart_fp.h"
#endif
#if CC_SequenceUpdate
#include "TPM/TPMCmd/tpm/include/private/prototypes/SequenceUpdate_fp.h"
#endif
#if CC_SequenceComplete
#include "TPM/TPMCmd/tpm/include/private/prototypes/SequenceComplete_fp.h"
#endif
#if CC_EventSequenceComplete
#include "TPM/TPMCmd/tpm/include/private/prototypes/EventSequenceComplete_fp.h"
#endif
#if CC_Certify
#include "TPM/TPMCmd/tpm/include/private/prototypes/Certify_fp.h"
#endif
#if CC_CertifyCreation
#include "TPM/TPMCmd/tpm/include/private/prototypes/CertifyCreation_fp.h"
#endif
#if CC_Quote
#include "TPM/TPMCmd/tpm/include/private/prototypes/Quote_fp.h"
#endif
#if CC_GetSessionAuditDigest
#include "TPM/TPMCmd/tpm/include/private/prototypes/GetSessionAuditDigest_fp.h"
#endif
#if CC_GetCommandAuditDigest
#include "TPM/TPMCmd/tpm/include/private/prototypes/GetCommandAuditDigest_fp.h"
#endif
#if CC_GetTime
#include "TPM/TPMCmd/tpm/include/private/prototypes/GetTime_fp.h"
#endif
#if CC_CertifyX509
#include "TPM/TPMCmd/tpm/include/private/prototypes/CertifyX509_fp.h"
#endif
#if CC_Commit
#include "TPM/TPMCmd/tpm/include/private/prototypes/Commit_fp.h"
#endif
#if CC_EC_Ephemeral
#include "TPM/TPMCmd/tpm/include/private/prototypes/EC_Ephemeral_fp.h"
#endif
#if CC_VerifySignature
#include "TPM/TPMCmd/tpm/include/private/prototypes/VerifySignature_fp.h"
#endif
#if CC_Sign
#include "TPM/TPMCmd/tpm/include/private/prototypes/Sign_fp.h"
#endif
#if CC_SetCommandCodeAuditStatus
#include "TPM/TPMCmd/tpm/include/private/prototypes/SetCommandCodeAuditStatus_fp.h"
#endif
#if CC_PCR_Extend
#include "TPM/TPMCmd/tpm/include/private/prototypes/PCR_Extend_fp.h"
#endif
#if CC_PCR_Event
#include "TPM/TPMCmd/tpm/include/private/prototypes/PCR_Event_fp.h"
#endif
#if CC_PCR_Read
#include "TPM/TPMCmd/tpm/include/private/prototypes/PCR_Read_fp.h"
#endif
#if CC_PCR_Allocate
#include "TPM/TPMCmd/tpm/include/private/prototypes/PCR_Allocate_fp.h"
#endif
#if CC_PCR_SetAuthPolicy
#include "TPM/TPMCmd/tpm/include/private/prototypes/PCR_SetAuthPolicy_fp.h"
#endif
#if CC_PCR_SetAuthValue
#include "TPM/TPMCmd/tpm/include/private/prototypes/PCR_SetAuthValue_fp.h"
#endif
#if CC_PCR_Reset
#include "TPM/TPMCmd/tpm/include/private/prototypes/PCR_Reset_fp.h"
#endif
#if CC_PolicySigned
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicySigned_fp.h"
#endif
#if CC_PolicySecret
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicySecret_fp.h"
#endif
#if CC_PolicyTicket
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicyTicket_fp.h"
#endif
#if CC_PolicyOR
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicyOR_fp.h"
#endif
#if CC_PolicyPCR
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicyPCR_fp.h"
#endif
#if CC_PolicyLocality
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicyLocality_fp.h"
#endif
#if CC_PolicyNV
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicyNV_fp.h"
#endif
#if CC_PolicyCounterTimer
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicyCounterTimer_fp.h"
#endif
#if CC_PolicyCommandCode
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicyCommandCode_fp.h"
#endif
#if CC_PolicyPhysicalPresence
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicyPhysicalPresence_fp.h"
#endif
#if CC_PolicyCpHash
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicyCpHash_fp.h"
#endif
#if CC_PolicyNameHash
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicyNameHash_fp.h"
#endif
#if CC_PolicyDuplicationSelect
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicyDuplicationSelect_fp.h"
#endif
#if CC_PolicyAuthorize
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicyAuthorize_fp.h"
#endif
#if CC_PolicyAuthValue
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicyAuthValue_fp.h"
#endif
#if CC_PolicyPassword
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicyPassword_fp.h"
#endif
#if CC_PolicyGetDigest
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicyGetDigest_fp.h"
#endif
#if CC_PolicyNvWritten
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicyNvWritten_fp.h"
#endif
#if CC_PolicyTemplate
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicyTemplate_fp.h"
#endif
#if CC_PolicyAuthorizeNV
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicyAuthorizeNV_fp.h"
#endif
#if CC_PolicyCapability
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicyCapability_fp.h"
#endif
#if CC_PolicyParameters
#include "TPM/TPMCmd/tpm/include/private/prototypes/PolicyParameters_fp.h"
#endif
#if CC_CreatePrimary
#include "TPM/TPMCmd/tpm/include/private/prototypes/CreatePrimary_fp.h"
#endif
#if CC_HierarchyControl
#include "TPM/TPMCmd/tpm/include/private/prototypes/HierarchyControl_fp.h"
#endif
#if CC_SetPrimaryPolicy
#include "TPM/TPMCmd/tpm/include/private/prototypes/SetPrimaryPolicy_fp.h"
#endif
#if CC_ChangePPS
#include "TPM/TPMCmd/tpm/include/private/prototypes/ChangePPS_fp.h"
#endif
#if CC_ChangeEPS
#include "TPM/TPMCmd/tpm/include/private/prototypes/ChangeEPS_fp.h"
#endif
#if CC_Clear
#include "TPM/TPMCmd/tpm/include/private/prototypes/Clear_fp.h"
#endif
#if CC_ClearControl
#include "TPM/TPMCmd/tpm/include/private/prototypes/ClearControl_fp.h"
#endif
#if CC_HierarchyChangeAuth
#include "TPM/TPMCmd/tpm/include/private/prototypes/HierarchyChangeAuth_fp.h"
#endif
#if CC_DictionaryAttackLockReset
#include "TPM/TPMCmd/tpm/include/private/prototypes/DictionaryAttackLockReset_fp.h"
#endif
#if CC_DictionaryAttackParameters
#include "TPM/TPMCmd/tpm/include/private/prototypes/DictionaryAttackParameters_fp.h"
#endif
#if CC_PP_Commands
#include "TPM/TPMCmd/tpm/include/private/prototypes/PP_Commands_fp.h"
#endif
#if CC_SetAlgorithmSet
#include "TPM/TPMCmd/tpm/include/private/prototypes/SetAlgorithmSet_fp.h"
#endif
#if CC_FieldUpgradeStart
#include "TPM/TPMCmd/tpm/include/private/prototypes/FieldUpgradeStart_fp.h"
#endif
#if CC_FieldUpgradeData
#include "TPM/TPMCmd/tpm/include/private/prototypes/FieldUpgradeData_fp.h"
#endif
#if CC_FirmwareRead
#include "TPM/TPMCmd/tpm/include/private/prototypes/FirmwareRead_fp.h"
#endif
#if CC_ContextSave
#include "TPM/TPMCmd/tpm/include/private/prototypes/ContextSave_fp.h"
#endif
#if CC_ContextLoad
#include "TPM/TPMCmd/tpm/include/private/prototypes/ContextLoad_fp.h"
#endif
#if CC_FlushContext
#include "TPM/TPMCmd/tpm/include/private/prototypes/FlushContext_fp.h"
#endif
#if CC_EvictControl
#include "TPM/TPMCmd/tpm/include/private/prototypes/EvictControl_fp.h"
#endif
#if CC_ReadClock
#include "TPM/TPMCmd/tpm/include/private/prototypes/ReadClock_fp.h"
#endif
#if CC_ClockSet
#include "TPM/TPMCmd/tpm/include/private/prototypes/ClockSet_fp.h"
#endif
#if CC_ClockRateAdjust
#include "TPM/TPMCmd/tpm/include/private/prototypes/ClockRateAdjust_fp.h"
#endif
#if CC_GetCapability
#include "TPM/TPMCmd/tpm/include/private/prototypes/GetCapability_fp.h"
#endif
#if CC_TestParms
#include "TPM/TPMCmd/tpm/include/private/prototypes/TestParms_fp.h"
#endif
#if CC_NV_DefineSpace
#include "TPM/TPMCmd/tpm/include/private/prototypes/NV_DefineSpace_fp.h"
#endif
#if CC_NV_UndefineSpace
#include "TPM/TPMCmd/tpm/include/private/prototypes/NV_UndefineSpace_fp.h"
#endif
#if CC_NV_UndefineSpaceSpecial
#include "TPM/TPMCmd/tpm/include/private/prototypes/NV_UndefineSpaceSpecial_fp.h"
#endif
#if CC_NV_ReadPublic
#include "TPM/TPMCmd/tpm/include/private/prototypes/NV_ReadPublic_fp.h"
#endif
#if CC_NV_Write
#include "TPM/TPMCmd/tpm/include/private/prototypes/NV_Write_fp.h"
#endif
#if CC_NV_Increment
#include "TPM/TPMCmd/tpm/include/private/prototypes/NV_Increment_fp.h"
#endif
#if CC_NV_Extend
#include "TPM/TPMCmd/tpm/include/private/prototypes/NV_Extend_fp.h"
#endif
#if CC_NV_SetBits
#include "TPM/TPMCmd/tpm/include/private/prototypes/NV_SetBits_fp.h"
#endif
#if CC_NV_WriteLock
#include "TPM/TPMCmd/tpm/include/private/prototypes/NV_WriteLock_fp.h"
#endif
#if CC_NV_GlobalWriteLock
#include "TPM/TPMCmd/tpm/include/private/prototypes/NV_GlobalWriteLock_fp.h"
#endif
#if CC_NV_Read
#include "TPM/TPMCmd/tpm/include/private/prototypes/NV_Read_fp.h"
#endif
#if CC_NV_ReadLock
#include "TPM/TPMCmd/tpm/include/private/prototypes/NV_ReadLock_fp.h"
#endif
#if CC_NV_ChangeAuth
#include "TPM/TPMCmd/tpm/include/private/prototypes/NV_ChangeAuth_fp.h"
#endif
#if CC_NV_Certify
#include "TPM/TPMCmd/tpm/include/private/prototypes/NV_Certify_fp.h"
#endif
#if CC_NV_DefineSpace2
#include "TPM/TPMCmd/tpm/include/private/prototypes/NV_DefineSpace2_fp.h"
#endif
#if CC_NV_ReadPublic2
#include "TPM/TPMCmd/tpm/include/private/prototypes/NV_ReadPublic2_fp.h"
#endif
#if CC_SetCapability
#include "TPM/TPMCmd/tpm/include/private/prototypes/SetCapability_fp.h"
#endif
#if CC_AC_Send
#include "TPM/TPMCmd/tpm/include/private/prototypes/AC_Send_fp.h"
#endif
#if CC_Policy_AC_SendSelect
#include "TPM/TPMCmd/tpm/include/private/prototypes/Policy_AC_SendSelect_fp.h"
#endif
#if CC_ACT_SetTimeout
#include "TPM/TPMCmd/tpm/include/private/prototypes/ACT_SetTimeout_fp.h"
#endif
#if CC_Vendor_TCG_Test
#include "TPM/TPMCmd/tpm/include/private/prototypes/Vendor_TCG_Test_fp.h"
#endif

#endif  // _COMMANDS_H_
